### ISSUE TITLE
Wrong number of arguments provided to the eliminated by message

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/Snake#8]
https://github.com/NucleoidMC/Snake/blob/81cab4aadbd5d414bee5c3d24f6a6e39d27bfdfa/src/main/java/net/puffish/snakemod/game/phase/SnakePlayingPhase.java#L65-L69

https://github.com/NucleoidMC/Snake/blob/81cab4aadbd5d414bee5c3d24f6a6e39d27bfdfa/src/main/resources/data/snake/lang/en_us.json#L11

**Comment by pufmat** [comment]
Yeah, I know. I just had no time to fix it, but thanks for taking a look at it.
